// 197 countries: 193 UN members + Vatican City, Palestine, Kosovo, Taiwan.
// code = ISO 3166-1 alpha-2, used to highlight the country on the map.
// aliases are accepted as answers (matching is case/accent/punctuation-insensitive).
const COUNTRIES = [
  // A
  { name: "Afghanistan", code: "AF" },
  { name: "Albania", code: "AL" },
  { name: "Algeria", code: "DZ" },
  { name: "Andorra", code: "AD" },
  { name: "Angola", code: "AO" },
  { name: "Antigua and Barbuda", code: "AG", aliases: ["Antigua & Barbuda", "Antigua"] },
  { name: "Argentina", code: "AR" },
  { name: "Armenia", code: "AM" },
  { name: "Australia", code: "AU" },
  { name: "Austria", code: "AT" },
  { name: "Azerbaijan", code: "AZ" },
  // B
  { name: "Bahamas", code: "BS", aliases: ["The Bahamas"] },
  { name: "Bahrain", code: "BH" },
  { name: "Bangladesh", code: "BD" },
  { name: "Barbados", code: "BB" },
  { name: "Belarus", code: "BY" },
  { name: "Belgium", code: "BE" },
  { name: "Belize", code: "BZ" },
  { name: "Benin", code: "BJ" },
  { name: "Bhutan", code: "BT" },
  { name: "Bolivia", code: "BO" },
  { name: "Bosnia and Herzegovina", code: "BA", aliases: ["Bosnia & Herzegovina", "Bosnia"] },
  { name: "Botswana", code: "BW" },
  { name: "Brazil", code: "BR" },
  { name: "Brunei", code: "BN", aliases: ["Brunei Darussalam"] },
  { name: "Bulgaria", code: "BG" },
  { name: "Burkina Faso", code: "BF" },
  { name: "Burundi", code: "BI" },
  // C
  { name: "Cambodia", code: "KH" },
  { name: "Cameroon", code: "CM" },
  { name: "Canada", code: "CA" },
  { name: "Cape Verde", code: "CV", aliases: ["Cabo Verde"] },
  { name: "Central African Republic", code: "CF", aliases: ["CAR"] },
  { name: "Chad", code: "TD" },
  { name: "Chile", code: "CL" },
  { name: "China", code: "CN", aliases: ["People's Republic of China", "PRC"] },
  { name: "Colombia", code: "CO" },
  { name: "Comoros", code: "KM" },
  { name: "Congo", code: "CG", aliases: ["Republic of the Congo", "Republic of Congo", "Congo-Brazzaville", "Congo Republic"] },
  { name: "Costa Rica", code: "CR" },
  { name: "Croatia", code: "HR" },
  { name: "Cuba", code: "CU" },
  { name: "Cyprus", code: "CY" },
  { name: "Czech Republic", code: "CZ", aliases: ["Czechia"] },
  // D
  { name: "Democratic Republic of the Congo", code: "CD", aliases: ["DR Congo", "DRC", "Democratic Republic of Congo", "Congo-Kinshasa", "Zaire"] },
  { name: "Denmark", code: "DK" },
  { name: "Djibouti", code: "DJ" },
  { name: "Dominica", code: "DM" },
  { name: "Dominican Republic", code: "DO" },
  // E
  { name: "East Timor", code: "TL", aliases: ["Timor-Leste", "Timor Leste"] },
  { name: "Ecuador", code: "EC" },
  { name: "Egypt", code: "EG" },
  { name: "El Salvador", code: "SV" },
  { name: "Equatorial Guinea", code: "GQ" },
  { name: "Eritrea", code: "ER" },
  { name: "Estonia", code: "EE" },
  { name: "Eswatini", code: "SZ", aliases: ["Swaziland"] },
  { name: "Ethiopia", code: "ET" },
  // F
  { name: "Fiji", code: "FJ" },
  { name: "Finland", code: "FI" },
  { name: "France", code: "FR" },
  // G
  { name: "Gabon", code: "GA" },
  { name: "Gambia", code: "GM", aliases: ["The Gambia"] },
  { name: "Georgia", code: "GE" },
  { name: "Germany", code: "DE" },
  { name: "Ghana", code: "GH" },
  { name: "Greece", code: "GR" },
  { name: "Grenada", code: "GD" },
  { name: "Guatemala", code: "GT" },
  { name: "Guinea", code: "GN" },
  { name: "Guinea-Bissau", code: "GW", aliases: ["Guinea Bissau"] },
  { name: "Guyana", code: "GY" },
  // H
  { name: "Haiti", code: "HT" },
  { name: "Honduras", code: "HN" },
  { name: "Hungary", code: "HU" },
  // I
  { name: "Iceland", code: "IS" },
  { name: "India", code: "IN" },
  { name: "Indonesia", code: "ID" },
  { name: "Iran", code: "IR" },
  { name: "Iraq", code: "IQ" },
  { name: "Ireland", code: "IE" },
  { name: "Israel", code: "IL" },
  { name: "Italy", code: "IT" },
  { name: "Ivory Coast", code: "CI", aliases: ["Cote d'Ivoire", "Côte d'Ivoire"] },
  // J
  { name: "Jamaica", code: "JM" },
  { name: "Japan", code: "JP" },
  { name: "Jordan", code: "JO" },
  // K
  { name: "Kazakhstan", code: "KZ" },
  { name: "Kenya", code: "KE" },
  { name: "Kiribati", code: "KI" },
  { name: "Kosovo", code: "XK" },
  { name: "Kuwait", code: "KW" },
  { name: "Kyrgyzstan", code: "KG" },
  // L
  { name: "Laos", code: "LA" },
  { name: "Latvia", code: "LV" },
  { name: "Lebanon", code: "LB" },
  { name: "Lesotho", code: "LS" },
  { name: "Liberia", code: "LR" },
  { name: "Libya", code: "LY" },
  { name: "Liechtenstein", code: "LI" },
  { name: "Lithuania", code: "LT" },
  { name: "Luxembourg", code: "LU" },
  // M
  { name: "Madagascar", code: "MG" },
  { name: "Malawi", code: "MW" },
  { name: "Malaysia", code: "MY" },
  { name: "Maldives", code: "MV" },
  { name: "Mali", code: "ML" },
  { name: "Malta", code: "MT" },
  { name: "Marshall Islands", code: "MH" },
  { name: "Mauritania", code: "MR" },
  { name: "Mauritius", code: "MU" },
  { name: "Mexico", code: "MX" },
  { name: "Micronesia", code: "FM", aliases: ["Federated States of Micronesia", "FSM"] },
  { name: "Moldova", code: "MD" },
  { name: "Monaco", code: "MC" },
  { name: "Mongolia", code: "MN" },
  { name: "Montenegro", code: "ME" },
  { name: "Morocco", code: "MA" },
  { name: "Mozambique", code: "MZ" },
  { name: "Myanmar", code: "MM", aliases: ["Burma"] },
  // N
  { name: "Namibia", code: "NA" },
  { name: "Nauru", code: "NR" },
  { name: "Nepal", code: "NP" },
  { name: "Netherlands", code: "NL", aliases: ["The Netherlands", "Holland"] },
  { name: "New Zealand", code: "NZ" },
  { name: "Nicaragua", code: "NI" },
  { name: "Niger", code: "NE" },
  { name: "Nigeria", code: "NG" },
  { name: "North Korea", code: "KP", aliases: ["DPRK", "Democratic People's Republic of Korea"] },
  { name: "North Macedonia", code: "MK", aliases: ["Macedonia"] },
  { name: "Norway", code: "NO" },
  // O
  { name: "Oman", code: "OM" },
  // P
  { name: "Pakistan", code: "PK" },
  { name: "Palau", code: "PW" },
  { name: "Palestine", code: "PS", aliases: ["State of Palestine"] },
  { name: "Panama", code: "PA" },
  { name: "Papua New Guinea", code: "PG", aliases: ["PNG"] },
  { name: "Paraguay", code: "PY" },
  { name: "Peru", code: "PE" },
  { name: "Philippines", code: "PH", aliases: ["The Philippines"] },
  { name: "Poland", code: "PL" },
  { name: "Portugal", code: "PT" },
  // Q
  { name: "Qatar", code: "QA" },
  // R
  { name: "Romania", code: "RO" },
  { name: "Russia", code: "RU", aliases: ["Russian Federation"] },
  { name: "Rwanda", code: "RW" },
  // S
  { name: "Saint Kitts and Nevis", code: "KN", aliases: ["St Kitts and Nevis", "St. Kitts and Nevis", "Saint Kitts", "St Kitts"] },
  { name: "Saint Lucia", code: "LC", aliases: ["St Lucia", "St. Lucia"] },
  { name: "Saint Vincent and the Grenadines", code: "VC", aliases: ["St Vincent and the Grenadines", "St. Vincent and the Grenadines", "Saint Vincent", "St Vincent"] },
  { name: "Samoa", code: "WS" },
  { name: "San Marino", code: "SM" },
  { name: "Sao Tome and Principe", code: "ST", aliases: ["São Tomé and Príncipe", "Sao Tome", "Sao Tome & Principe"] },
  { name: "Saudi Arabia", code: "SA" },
  { name: "Senegal", code: "SN" },
  { name: "Serbia", code: "RS" },
  { name: "Seychelles", code: "SC" },
  { name: "Sierra Leone", code: "SL" },
  { name: "Singapore", code: "SG" },
  { name: "Slovakia", code: "SK" },
  { name: "Slovenia", code: "SI" },
  { name: "Solomon Islands", code: "SB" },
  { name: "Somalia", code: "SO" },
  { name: "South Africa", code: "ZA" },
  { name: "South Korea", code: "KR", aliases: ["Republic of Korea", "ROK"] },
  { name: "South Sudan", code: "SS" },
  { name: "Spain", code: "ES" },
  { name: "Sri Lanka", code: "LK" },
  { name: "Sudan", code: "SD" },
  { name: "Suriname", code: "SR", aliases: ["Surinam"] },
  { name: "Sweden", code: "SE" },
  { name: "Switzerland", code: "CH" },
  { name: "Syria", code: "SY", aliases: ["Syrian Arab Republic"] },
  // T
  { name: "Taiwan", code: "TW", aliases: ["Republic of China", "Chinese Taipei"] },
  { name: "Tajikistan", code: "TJ" },
  { name: "Tanzania", code: "TZ" },
  { name: "Thailand", code: "TH" },
  { name: "Togo", code: "TG" },
  { name: "Tonga", code: "TO" },
  { name: "Trinidad and Tobago", code: "TT", aliases: ["Trinidad & Tobago", "Trinidad"] },
  { name: "Tunisia", code: "TN" },
  { name: "Turkey", code: "TR", aliases: ["Türkiye", "Turkiye"] },
  { name: "Turkmenistan", code: "TM" },
  { name: "Tuvalu", code: "TV" },
  // U
  { name: "Uganda", code: "UG" },
  { name: "Ukraine", code: "UA" },
  { name: "United Arab Emirates", code: "AE", aliases: ["UAE", "Emirates"] },
  { name: "United Kingdom", code: "GB", aliases: ["UK", "Great Britain", "Britain"] },
  { name: "United States", code: "US", aliases: ["United States of America", "USA", "US", "America"] },
  { name: "Uruguay", code: "UY" },
  { name: "Uzbekistan", code: "UZ" },
  // V
  { name: "Vanuatu", code: "VU" },
  { name: "Vatican City", code: "VA", aliases: ["Vatican", "Holy See"] },
  { name: "Venezuela", code: "VE" },
  { name: "Vietnam", code: "VN", aliases: ["Viet Nam"] },
  // Y
  { name: "Yemen", code: "YE" },
  // Z
  { name: "Zambia", code: "ZM" },
  { name: "Zimbabwe", code: "ZW" },
];
